### ISSUE TITLE
Возможность передачи лидерки в банде

### ISSUE THREAD

**Issue by ziggi** [Open-GTO/Open-GTO#6]
Сделать возможность лидеру банды передать права другому игроку, реализовать после #4.

**Comment by thetruesteepname** [comment]
а если же аккаунт будет взломан?
можно будет отдать банду со всей ее статистикой, конечно во всяком случае ее можно удалить и забрать все деньги из банка банды, но в #4 лучше сделать так, чтобы заместитель мог и принимать игроков банду, как и удалять (кроме лидера), тем самым при длительном отсутствии создателя на банду это не как не повлияет и передача лидерки не нужна, в следствие - и лишняя работа над этим
